### PR TITLE
template.gistic.meta.json: Add min and max

### PR DESCRIPTION
**Pull request by ayan-b**
Closes https://github.com/yunhailuo/xena-GDC-ETL/issues/61

### CODE REVIEW

**Comment by yunhailuo** [comment]
Can we try one matrix with those changes (meaning doesn't have to be from dece5370552ddc317758aa5ad09e68766d4983ff). I'm wondering if those digits matters and would like to be sure it works as @maryjgoldman expected. The patch seems quite right.

**Comment by ayan-b** [comment]
Added for TCGA-CHOL in the hub.

**Comment by maryjgoldman** [comment]
So to look at this I should look at the hub for the GISTIC CHOL dataset?

**Comment by yunhailuo** [comment]
> So to look at this I should look at the hub for the GISTIC CHOL dataset?

I guess so, @ayan-b ?

**Comment by ayan-b** [comment]
Yes.

**Pull request merged**
